export const staticData = [
    {
      id: 1,
      number: 30,
      name: "Curry",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 1
    },
    {
      id: 2,
      number: 23,
      name: "Jordan",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 1
    },
    {
      id: 3,
      number: 6,
      name: "James",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 1
    },
    {
      id: 4,
      number: 10,
      name: "Gordon",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 1
    },
    {
      id: 5,
      number: 3,
      name: "Iverson",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 1
    },
    {
      id: 6,
      number: 13,
      name: "Adebayo",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 1
    },
    {
      id: 7,
      number: 5,
      name: "Brown",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 1
    },
    // {
    //   id: 3,
    //   number: 6,
    //   name: "James",
    //   pts: 0,
    //   rebs: 0,
    //   ast: 0,
    //   stl: 0,
    //   blk: 0,
    //   fgMake: 0,
    //   fgAttempt: 0,
    //   fgMakeAttemptPercent: 0,
    //   ftMake: 0,
    //   ftAttempt: 0,
    //   ftMakeAttemptPercent: 0,
    //   threePtMake: 0,
    //   threePtAttempt: 0,
    //   threePtMakeAttemptPercent: 0,
    //   totalFgMake: 0,
    //   totalFgAttempt: 0,
    //   totalFgMakeAttemptPercent: 0,
    //   tov: 0,
    //   fls: 0,
    //   team: 1
    // },
    // {
    //   id: 4,
    //   number: 10,
    //   name: "Gordon",
    //   pts: 0,
    //   rebs: 0,
    //   ast: 0,
    //   stl: 0,
    //   blk: 0,
    //   fgMake: 0,
    //   fgAttempt: 0,
    //   fgMakeAttemptPercent: 0,
    //   ftMake: 0,
    //   ftAttempt: 0,
    //   ftMakeAttemptPercent: 0,
    //   threePtMake: 0,
    //   threePtAttempt: 0,
    //   threePtMakeAttemptPercent: 0,
    //   totalFgMake: 0,
    //   totalFgAttempt: 0,
    //   totalFgMakeAttemptPercent: 0,
    //   tov: 0,
    //   fls: 0,
    //   team: 1
    // },
    // {
    //   id: 5,
    //   number: 3,
    //   name: "Iverson",
    //   pts: 0,
    //   rebs: 0,
    //   ast: 0,
    //   stl: 0,
    //   blk: 0,
    //   fgMake: 0,
    //   fgAttempt: 0,
    //   fgMakeAttemptPercent: 0,
    //   ftMake: 0,
    //   ftAttempt: 0,
    //   ftMakeAttemptPercent: 0,
    //   threePtMake: 0,
    //   threePtAttempt: 0,
    //   threePtMakeAttemptPercent: 0,
    //   totalFgMake: 0,
    //   totalFgAttempt: 0,
    //   totalFgMakeAttemptPercent: 0,
    //   tov: 0,
    //   fls: 0,
    //   team: 1
    // },
    // {
    //   id: 1,
    //   number: 30,
    //   name: "Curry",
    //   pts: 0,
    //   rebs: 0,
    //   ast: 0,
    //   stl: 0,
    //   blk: 0,
    //   fgMake: 0,
    //   fgAttempt: 0,
    //   fgMakeAttemptPercent: 0,
    //   ftMake: 0,
    //   ftAttempt: 0,
    //   ftMakeAttemptPercent: 0,
    //   threePtMake: 0,
    //   threePtAttempt: 0,
    //   threePtMakeAttemptPercent: 0,
    //   totalFgMake: 0,
    //   totalFgAttempt: 0,
    //   totalFgMakeAttemptPercent: 0,
    //   tov: 0,
    //   fls: 0,
    //   team: 1
    // },
    // {
    //   id: 2,
    //   number: 23,
    //   name: "Jordan",
    //   pts: 0,
    //   rebs: 0,
    //   ast: 0,
    //   stl: 0,
    //   blk: 0,
    //   fgMake: 0,
    //   fgAttempt: 0,
    //   fgMakeAttemptPercent: 0,
    //   ftMake: 0,
    //   ftAttempt: 0,
    //   ftMakeAttemptPercent: 0,
    //   threePtMake: 0,
    //   threePtAttempt: 0,
    //   threePtMakeAttemptPercent: 0,
    //   totalFgMake: 0,
    //   totalFgAttempt: 0,
    //   totalFgMakeAttemptPercent: 0,
    //   tov: 0,
    //   fls: 0,
    //   team: 1
    // },
    // {
    //   id: 3,
    //   number: 6,
    //   name: "James",
    //   pts: 0,
    //   rebs: 0,
    //   ast: 0,
    //   stl: 0,
    //   blk: 0,
    //   fgMake: 0,
    //   fgAttempt: 0,
    //   fgMakeAttemptPercent: 0,
    //   ftMake: 0,
    //   ftAttempt: 0,
    //   ftMakeAttemptPercent: 0,
    //   threePtMake: 0,
    //   threePtAttempt: 0,
    //   threePtMakeAttemptPercent: 0,
    //   totalFgMake: 0,
    //   totalFgAttempt: 0,
    //   totalFgMakeAttemptPercent: 0,
    //   tov: 0,
    //   fls: 0,
    //   team: 1
    // },
    // {
    //   id: 4,
    //   number: 10,
    //   name: "Gordon",
    //   pts: 0,
    //   rebs: 0,
    //   ast: 0,
    //   stl: 0,
    //   blk: 0,
    //   fgMake: 0,
    //   fgAttempt: 0,
    //   fgMakeAttemptPercent: 0,
    //   ftMake: 0,
    //   ftAttempt: 0,
    //   ftMakeAttemptPercent: 0,
    //   threePtMake: 0,
    //   threePtAttempt: 0,
    //   threePtMakeAttemptPercent: 0,
    //   totalFgMake: 0,
    //   totalFgAttempt: 0,
    //   totalFgMakeAttemptPercent: 0,
    //   tov: 0,
    //   fls: 0,
    //   team: 1
    // },
    // {
    //   id: 5,
    //   number: 15,
    //   name: "Iverson",
    //   pts: 0,
    //   rebs: 0,
    //   ast: 0,
    //   stl: 0,
    //   blk: 0,
    //   fgMake: 0,
    //   fgAttempt: 0,
    //   fgMakeAttemptPercent: 0,
    //   ftMake: 0,
    //   ftAttempt: 0,
    //   ftMakeAttemptPercent: 0,
    //   threePtMake: 0,
    //   threePtAttempt: 0,
    //   threePtMakeAttemptPercent: 0,
    //   totalFgMake: 0,
    //   totalFgAttempt: 0,
    //   totalFgMakeAttemptPercent: 0,
    //   tov: 0,
    //   fls: 0,
    //   team: 1
    // },
    {
      id: 21,
      number: 6,
      name: "Davis",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 2
    },
    {
      id: 22,
      number: 17,
      name: "Reddick",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 2
    },
    {
      id: 23,
      number: 5,
      name: "Edwards",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 2
    },
    {
      id: 24,
      number: 0,
      name: "Tatum",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 2
    },
    {
      id: 25,
      number: 23,
      name: "Rose",
      isActive: false,
      pts: 0,
      rebs: 0,
      ast: 0,
      stl: 0,
      blk: 0,
      fgMake: 0,
      fgAttempt: 0,
      fgMakeAttemptPercent: 0,
      ftMake: 0,
      ftAttempt: 0,
      ftMakeAttemptPercent: 0,
      threePtMake: 0,
      threePtAttempt: 0,
      threePtMakeAttemptPercent: 0,
      totalFgMake: 0,
      totalFgAttempt: 0,
      totalFgMakeAttemptPercent: 0,
      tov: 0,
      fls: 0,
      team: 2
    }
]