export const StatTypes = {
    Pts: 0,
    Rebs: 1,
    Ast: 2,
    Stl: 3,
    Blk: 4,
    FgMake: 5,
    FgAttempt: 6,
    FgMakeAttemptPercent: 7,
    FtMake: 8,
    FtAttempt: 9,
    FtMakeAttemptPercent: 10,
    ThreePtMake: 11,
    ThreePtAttempt: 12,
    ThreePtMakeAttemptPercent: 13,
    TotalFgMake: 14,
    TotalFgAttempt: 15,
    TotalFgMakeAttemptPercent: 16,
    Tov: 17,
    Fls: 18,
}